tap "homebrew/bundle"
brew "jq"
brew "tmux"
cask "appcleaner"
# cask "dropbox"
# cask "docker"
cask "google-chrome"
cask "google-drive"
cask "karabiner-elements"
cask "keepassxc"
cask "skype"
cask "teamviewer"
cask "zoom"
