tap "homebrew/bundle"
brew "jq"
brew "tmux"
cask "airdroid"
cask "appcleaner"
# cask "dropbox"
# cask "docker"
casl "google-chrome"
cask "karabiner-elements"
cask "keepassxc"
cask "mmhmm"
cask "skype"
cask "teamviewer"
cask "zoom"
