tap "homebrew/bundle"
tap "homebrew/cask"
brew "jq"
brew "tmux"
cask "appcleaner"
# cask "dropbox"
# cask "docker"
casl "google-chrome"
cask "karabiner-elements"
cask "keepassxc"
cask "lunar"
cask "skype"
cask "zoomus"
